@extends('layouts.app')

@section('title', 'Privacy Policy - Points Counter')
@section('description', 'Privacy Policy for Points Counter mobile application')
@section('page_url', route('pointscounter.privacy.en'))

@section('custom_css')
    @parent
@endsection

@section('sidebar')
    @parent
    <link href="assets/css/custom.css?v={{ filemtime(public_path('assets/css/custom.css')) }}" rel="stylesheet" type="text/css" media="all"/>
@endsection

@section('content')
    @include('layouts.navbar_white', ['active_menu_item' => $active_menu_item])

    <section class="container-fluid py-0">
        <div class="row">
            <div class="col-12 col-md-3 col-lg-2 border-right pt-3 pt-md-5 docs-sidebar">
                <div id="docs-index" class="collapse">
                    <div class="mb-3 mb-md-4">
                        <h6 class="mb-2">Privacy Policy</h6>
                    </div>
                </div>
            </div>
            <div class="col-md-9 col-lg-10">
                <div class="row">
                    <div class="col-xl-10 col-lg-9 px-xl-6 px-lg-4 px-md-3 py-md-5">
                        <div class="card card-body card-lg shadow-3d rounded-sm mb-4 mb-md-5">
                            <h1>Privacy Policy</h1>
                            <div class="lead">
                                <p><strong>Last Updated:</strong> January 2, 2026</p>
                                <p>PointsCounter ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our mobile application (the "App").</p>
                                <p><a href="{{ route('pointscounter.privacy') }}">Русская версия</a></p>
                            </div>
                        </div>

                        <article id="introduction" class="mb-4 mb-md-6">
                            <h3>Introduction</h3>
                            <div>
                                <p>PointsCounter ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our mobile application (the "App").</p>
                            </div>
                        </article>

                        <article id="information-we-collect" class="mb-4 mb-md-6">
                            <h3>Information We Collect</h3>
                            
                            <h4>1. Device Information</h4>
                            <div>
                                <p>When you first launch the App, we collect the following device information to create your user account:</p>
                                <ul>
                                    <li><strong>Device Model</strong> (e.g., "iPhone", "iPad")</li>
                                    <li><strong>Operating System Version</strong> (e.g., iOS version)</li>
                                    <li><strong>App Version</strong></li>
                                    <li><strong>Locale</strong> (language and region settings)</li>
                                </ul>
                                <p>This information is used solely to generate a unique user identifier and ensure compatibility with your device.</p>
                            </div>

                            <h4>2. User Identifier</h4>
                            <div>
                                <p>We generate and assign a unique device identifier (UUID) that is stored on your device and associated with your account. This identifier:</p>
                                <ul>
                                    <li>Is generated by our servers (never by your device)</li>
                                    <li>Remains constant unless you manually clear app data</li>
                                    <li>Is used to associate your activities and participation in games with your account</li>
                                </ul>
                            </div>

                            <h4>3. User-Provided Information</h4>
                            <div>
                                <ul>
                                    <li><strong>Name</strong>: You may provide your name when joining or creating a game. This name is visible to other participants in the same game.</li>
                                    <li><strong>Game Data</strong>: Information about games you create or join, including:
                                        <ul>
                                            <li>Game titles</li>
                                            <li>Game types</li>
                                            <li>Initial scores</li>
                                            <li>Participant information (names, scores, purchases)</li>
                                            <li>Game results and calculations</li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>

                            <h4>4. Push Notification Token</h4>
                            <div>
                                <p>If you grant permission, we collect your device's push notification token to send you notifications about:</p>
                                <ul>
                                    <li>Game start events</li>
                                    <li>New participant joins</li>
                                    <li>Other game-related updates</li>
                                </ul>
                                <p>You can revoke this permission at any time through your device settings.</p>
                            </div>

                            <h4>5. Camera Access</h4>
                            <div>
                                <p>The App requests camera access to scan QR codes for joining games. Camera data is processed locally on your device and is never transmitted to our servers. We only process the QR code content (invite code) extracted from the image.</p>
                            </div>
                        </article>

                        <article id="how-we-use" class="mb-4 mb-md-6">
                            <h3>How We Use Your Information</h3>
                            <div>
                                <p>We use the collected information to:</p>
                                <ul>
                                    <li><strong>Provide App Functionality</strong>: Enable you to create and join games, track scores, and calculate results</li>
                                    <li><strong>Send Notifications</strong>: Inform you about game events (only if you grant permission)</li>
                                    <li><strong>Maintain Your Account</strong>: Associate your activities with your account using your device identifier</li>
                                    <li><strong>Improve the App</strong>: Use device and app version information for compatibility and troubleshooting</li>
                                </ul>
                            </div>
                        </article>

                        <article id="data-storage" class="mb-4 mb-md-6">
                            <h3>Data Storage and Security</h3>
                            
                            <h4>Local Storage</h4>
                            <div>
                                <ul>
                                    <li>User identifier, name, and game data are stored locally on your device using iOS UserDefaults</li>
                                    <li>This data remains on your device and is not automatically synced to other devices</li>
                                </ul>
                            </div>

                            <h4>Server Storage</h4>
                            <div>
                                <ul>
                                    <li>Your device identifier is stored on our servers to maintain your account</li>
                                    <li>Game data (titles, participants, scores) is stored on our servers to enable multiplayer functionality</li>
                                    <li>All data transmission uses HTTPS encryption</li>
                                </ul>
                            </div>

                            <h4>Data Retention</h4>
                            <div>
                                <ul>
                                    <li>Your account and game data are retained as long as you use the App</li>
                                    <li>You can delete your local data by clearing the App's data in iOS Settings</li>
                                    <li>Server-side data may be retained for a reasonable period after account deletion for backup and recovery purposes</li>
                                </ul>
                            </div>
                        </article>

                        <article id="data-sharing" class="mb-4 mb-md-6">
                            <h3>Data Sharing</h3>
                            <div>
                                <p>We do <strong>NOT</strong>:</p>
                                <ul>
                                    <li>Sell your personal information to third parties</li>
                                    <li>Share your information with advertisers</li>
                                    <li>Use tracking or analytics services</li>
                                    <li>Collect information for marketing purposes</li>
                                </ul>
                                <p>We only share your information:</p>
                                <ul>
                                    <li><strong>With Other Participants</strong>: Your name and game-related data are visible to other participants in the same game</li>
                                    <li><strong>As Required by Law</strong>: If required by applicable laws or legal processes</li>
                                </ul>
                            </div>
                        </article>

                        <article id="your-rights" class="mb-4 mb-md-6">
                            <h3>Your Rights</h3>
                            <div>
                                <p>You have the right to:</p>
                                <ul>
                                    <li><strong>Access Your Data</strong>: View the data stored on your device through the App</li>
                                    <li><strong>Delete Your Data</strong>: Clear app data through iOS Settings</li>
                                    <li><strong>Opt-Out of Notifications</strong>: Disable push notifications through iOS Settings</li>
                                    <li><strong>Revoke Camera Access</strong>: Disable camera access through iOS Settings</li>
                                </ul>
                            </div>
                        </article>

                        <article id="children-privacy" class="mb-4 mb-md-6">
                            <h3>Children's Privacy</h3>
                            <div>
                                <p>The App is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe we have collected information from a child under 13, please contact us immediately.</p>
                            </div>
                        </article>

                        <article id="changes" class="mb-4 mb-md-6">
                            <h3>Changes to This Privacy Policy</h3>
                            <div>
                                <p>We may update this Privacy Policy from time to time. We will notify you of any changes by updating the "Last Updated" date at the top of this policy. You are advised to review this Privacy Policy periodically for any changes.</p>
                            </div>
                        </article>

                        <article id="contact" class="mb-4 mb-md-6">
                            <h3>Contact Us</h3>
                            <div>
                                <p>If you have any questions about this Privacy Policy, please contact us at:</p>
                                <ul>
                                    <li><strong>Email</strong>: <a href="mailto:e@mpleev.com">e@mpleev.com</a></li>
                                    <li><strong>Website</strong>: <a href="https://pointscounter.ampleev.com">https://pointscounter.ampleev.com</a></li>
                                </ul>
                            </div>
                        </article>

                        <article id="compliance" class="mb-4 mb-md-6">
                            <h3>Compliance</h3>
                            <div>
                                <p>This Privacy Policy complies with:</p>
                                <ul>
                                    <li>Apple App Store requirements</li>
                                    <li>General Data Protection Regulation (GDPR) for EU users</li>
                                    <li>California Consumer Privacy Act (CCPA) for California residents</li>
                                </ul>
                            </div>
                        </article>

                        <div class="card card-body card-lg shadow-3d rounded-sm mb-4 mb-md-5">
                            <p><strong>Note</strong>: This Privacy Policy applies only to the PointsCounter mobile application. If you access our website, please review the website's privacy policy separately.</p>
                        </div>

                    </div>
                    <div class="col-xl-2 col-lg-3 d-none d-lg-block py-md-5 docs-sidebar">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a href="#introduction" class="nav-link text-small" data-smooth-scroll>Introduction</a>
                            </li>
                            <li class="nav-item">
                                <a href="#information-we-collect" class="nav-link text-small" data-smooth-scroll>Information We Collect</a>
                            </li>
                            <li class="nav-item">
                                <a href="#how-we-use" class="nav-link text-small" data-smooth-scroll>How We Use Your Information</a>
                            </li>
                            <li class="nav-item">
                                <a href="#data-storage" class="nav-link text-small" data-smooth-scroll>Data Storage and Security</a>
                            </li>
                            <li class="nav-item">
                                <a href="#data-sharing" class="nav-link text-small" data-smooth-scroll>Data Sharing</a>
                            </li>
                            <li class="nav-item">
                                <a href="#your-rights" class="nav-link text-small" data-smooth-scroll>Your Rights</a>
                            </li>
                            <li class="nav-item">
                                <a href="#children-privacy" class="nav-link text-small" data-smooth-scroll>Children's Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a href="#changes" class="nav-link text-small" data-smooth-scroll>Changes to This Policy</a>
                            </li>
                            <li class="nav-item">
                                <a href="#contact" class="nav-link text-small" data-smooth-scroll>Contact Us</a>
                            </li>
                            <li class="nav-item">
                                <a href="#compliance" class="nav-link text-small" data-smooth-scroll>Compliance</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

@section('pageScript')
    @parent
@endsection

