<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SitePageVisit extends Model
{
    protected $fillable = [
        'event_name',
        'visitor_key',
        'session_key',
        'page_url',
        'page_path',
        'page_query',
        'page_title',
        'canonical_url',
        'locale',
        'client_referrer',
        'client_referrer_host',
        'client_referrer_path',
        'utm_source',
        'utm_medium',
        'utm_campaign',
        'utm_content',
        'utm_term',
        'attribution_source',
        'attribution_medium',
        'attribution_campaign',
        'attribution_content',
        'first_attribution_source',
        'first_attribution_medium',
        'first_attribution_campaign',
        'first_attribution_content',
        'request_host',
        'request_scheme',
        'request_referer',
        'request_referer_host',
        'request_referer_path',
        'user_agent',
        'accept_language',
        'primary_language',
        'sec_ch_ua',
        'sec_ch_ua_mobile',
        'sec_ch_ua_platform',
        'ip_hash',
        'ip_encrypted',
        'forwarded_for_hash',
        'real_ip_hash',
        'ip_version',
        'ip_is_private',
        'device_type',
        'device_name',
        'platform_name',
        'platform_version',
        'browser_name',
        'browser_version',
        'is_robot',
        'robot_name',
        'user_id',
        'is_admin',
        'client_timezone',
        'client_timezone_offset',
        'client_language',
        'client_languages',
        'client_platform',
        'client_vendor',
        'client_cookie_enabled',
        'client_do_not_track',
        'client_screen_width',
        'client_screen_height',
        'client_available_width',
        'client_available_height',
        'client_viewport_width',
        'client_viewport_height',
        'client_device_pixel_ratio',
        'client_color_depth',
        'client_pixel_depth',
        'client_max_touch_points',
        'client_hardware_concurrency',
        'client_device_memory',
        'client_connection_type',
        'client_effective_connection_type',
        'client_downlink',
        'client_rtt',
        'client_save_data',
        'client_touch_supported',
        'client_standalone',
        'client_visibility_state',
        'client_local_time',
        'server_payload',
        'client_payload',
    ];

    protected $casts = [
        'ip_is_private' => 'boolean',
        'is_robot' => 'boolean',
        'is_admin' => 'boolean',
        'client_cookie_enabled' => 'boolean',
        'client_save_data' => 'boolean',
        'client_touch_supported' => 'boolean',
        'client_standalone' => 'boolean',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
