<?php

namespace App\Http\Controllers;

use App\Services\Yai\YaiChatService;
use App\Support\SiteLocale;
use Illuminate\Http\Request;

class YaiChatController extends Controller
{
    public function show()
    {
        abort_unless(config('yai.enabled'), 404);

        $currentLocale = SiteLocale::resolve(request());
        $active_menu_item = 'ЯAI';

        $copy = $currentLocale === 'en'
            ? [
                'title' => 'YAI — chat with my digital twin',
                'description' => 'Ask my AI twin about product processes, Agile transformation and working with AI agents — it answers based on my articles.',
                'heading' => 'YAI',
                'subheading' => 'My digital twin. Answers as me, based on my articles and materials. Experimental.',
                'placeholder' => 'Ask about product processes, Agile, AI…',
                'send' => 'Send',
                'disclaimer' => 'YAI is an experiment: answers are generated by a language model from my articles and may be inaccurate. For anything important — contact me directly.',
                'sources_label' => 'Sources',
                'greeting' => "Hi! I'm YAI — Evgeny's digital twin. Ask me about product processes, Agile transformation, AI in development teams — I answer based on his articles.",
                'error' => 'Request failed. Please try again.',
            ]
            : [
                'title' => 'ЯAI — чат с моим цифровым двойником',
                'description' => 'Спросите моего AI-двойника о продуктовых процессах, Agile-трансформации и работе с AI-агентами — он отвечает на основе моих статей.',
                'heading' => 'ЯAI',
                'subheading' => 'Мой цифровой двойник. Отвечает от моего имени на основе моих статей и материалов. Экспериментальная штука.',
                'placeholder' => 'Спросите про продуктовые процессы, Agile, AI…',
                'send' => 'Отправить',
                'disclaimer' => 'ЯAI — эксперимент: ответы генерирует языковая модель на основе моих статей, возможны неточности. По важным вопросам — пишите мне напрямую.',
                'sources_label' => 'Источники',
                'greeting' => 'Привет! Я — ЯAI, цифровой двойник Евгения. Спрашивайте про продуктовые процессы, Agile-трансформацию, AI в командах разработки — отвечаю на основе его статей.',
                'error' => 'Не получилось отправить запрос. Попробуйте ещё раз.',
            ];

        return view('yai.index', compact('active_menu_item', 'copy', 'currentLocale'));
    }

    public function chat(Request $request, YaiChatService $service)
    {
        abort_unless(config('yai.enabled'), 503);

        $maxChars = (int) config('yai.limits.max_message_chars', 1200);

        $validated = $request->validate([
            'message' => ['required', 'string', 'max:' . $maxChars],
            'history' => ['sometimes', 'array', 'max:' . (int) config('yai.limits.max_history_messages', 8)],
            'history.*.role' => ['required_with:history', 'string', 'in:user,assistant'],
            'history.*.content' => ['required_with:history', 'string', 'max:4000'],
            'locale' => ['sometimes', 'string', 'in:ru,en'],
        ]);

        $result = $service->answer(
            trim($validated['message']),
            $validated['history'] ?? [],
            $validated['locale'] ?? 'ru'
        );

        return response()->json($result);
    }
}
