<?php

namespace App\Http\Controllers;

use App\Services\Yai\YaiChatService;
use App\Support\SiteLocale;
use Illuminate\Http\Request;

class YaiChatController extends Controller
{
    public function show()
    {
        abort_unless(config('yai.enabled'), 404);

        $currentLocale = SiteLocale::resolve(request());

        return view('yai.index', $this->pageData($currentLocale));
    }

    /**
     * Временные страницы сравнения редизайна: /yai/v1 и /yai/v2.
     * Одна разметка, различия вариантов — CSS-модификаторами. Убрать после выбора.
     */
    public function preview(string $variant)
    {
        abort_unless(config('yai.enabled'), 404);
        abort_unless(in_array($variant, ['v1', 'v2'], true), 404);

        $currentLocale = SiteLocale::resolve(request());

        return view('yai.redesign', $this->pageData($currentLocale) + ['variant' => $variant]);
    }

    /**
     * Данные страницы. site_locale и locale_labels передаются во view явно:
     * глобальный View::share вычисляет локаль по cookie/гео ДО маршрутизации,
     * из-за чего /yai мог получать английские меню и футер при русском контенте.
     * Явная передача переопределяет расшаренные значения только для этих страниц.
     */
    private function pageData(string $locale): array
    {
        $isEn = $locale === 'en';

        $copy = $isEn
            ? [
                'title' => 'AIЯ — chat with my digital twin',
                'description' => 'Ask my AI twin about product processes, Agile transformation and working with AI agents — it answers based on my articles.',
                'heading' => 'AIЯ',
                'eyebrow' => 'Experiment · digital twin',
                'subheading' => 'My digital twin. Answers as me, based on my articles and materials.',
                'topics' => ['Agile', 'AI agents', 'delivery metrics', 'product processes'],
                'placeholder' => 'Ask about product processes, Agile, AI…',
                'input_label' => 'Your question to AIЯ',
                'send' => 'Send',
                'sending' => 'Sending…',
                'disclaimer' => 'AIЯ is an experiment: answers are generated by a language model from my articles and may be inaccurate. For anything important — contact me directly.',
                'disclaimer_lead' => 'AIЯ is an experiment: answers are generated by a language model from my articles and may be inaccurate. For anything important — ',
                'disclaimer_link' => 'contact me directly',
                'sources_label' => 'Sources',
                'greeting' => "Hi! I'm AIЯ — Evgeny's digital twin. Ask me about product processes, Agile transformation, AI in development teams — I answer based on his articles.",
                'error' => 'Request failed. Please try again.',
                'typing' => 'AIЯ is typing…',
            ]
            : [
                'title' => 'AIЯ — чат с моим цифровым двойником',
                'description' => 'Спросите моего AI-двойника о продуктовых процессах, Agile-трансформации и работе с AI-агентами — он отвечает на основе моих статей.',
                'heading' => 'AIЯ',
                'eyebrow' => 'Эксперимент · цифровой двойник',
                'subheading' => 'Мой цифровой двойник. Отвечает от моего имени на основе моих статей и материалов.',
                'topics' => ['Agile', 'AI-агенты', 'метрики delivery', 'продуктовые процессы'],
                'placeholder' => 'Спросите про продуктовые процессы, Agile, AI…',
                'input_label' => 'Ваш вопрос к AIЯ',
                'send' => 'Отправить',
                'sending' => 'Отправка…',
                'disclaimer' => 'AIЯ — эксперимент: ответы генерирует языковая модель на основе моих статей, возможны неточности. По важным вопросам — пишите мне напрямую.',
                'disclaimer_lead' => 'AIЯ — эксперимент: ответы генерирует языковая модель на основе моих статей, возможны неточности. По важным вопросам — ',
                'disclaimer_link' => 'пишите мне напрямую',
                'sources_label' => 'Источники',
                'greeting' => 'Привет! Я — AIЯ, цифровой двойник Евгения. Спрашивайте про продуктовые процессы, Agile-трансформацию, AI в командах разработки — отвечаю на основе его статей.',
                'error' => 'Не получилось отправить запрос. Попробуйте ещё раз.',
                'typing' => 'AIЯ печатает…',
            ];

        return [
            'active_menu_item' => 'aiya',
            'copy' => $copy,
            'currentLocale' => $locale,
            // Переопределяют View::share для согласованности layout с маршрутом
            'site_locale' => $locale,
            'locale_labels' => SiteLocale::labels($locale),
        ];
    }

    public function chat(Request $request, YaiChatService $service)
    {
        abort_unless(config('yai.enabled'), 503);

        $maxChars = (int) config('yai.limits.max_message_chars', 1200);

        $validated = $request->validate([
            'message' => ['required', 'string', 'max:' . $maxChars],
            'history' => ['sometimes', 'array', 'max:' . (int) config('yai.limits.max_history_messages', 8)],
            'history.*.role' => ['required_with:history', 'string', 'in:user,assistant'],
            'history.*.content' => ['required_with:history', 'string', 'max:4000'],
            'locale' => ['sometimes', 'string', 'in:ru,en'],
        ]);

        $result = $service->answer(
            trim($validated['message']),
            $validated['history'] ?? [],
            $validated['locale'] ?? 'ru'
        );

        return response()->json($result);
    }
}
